/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_altova_nativegui_NativeGUI */

#ifndef _Included_com_altova_nativegui_NativeGUI
#define _Included_com_altova_nativegui_NativeGUI
#ifdef __cplusplus
extern "C" {
#endif
#undef com_altova_nativegui_NativeGUI_CURRENT_VERSION
#define com_altova_nativegui_NativeGUI_CURRENT_VERSION 7L
/*
 * Class:     com_altova_nativegui_NativeGUI
 * Method:    getWindowRect
 * Signature: (II)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_altova_nativegui_NativeGUI_getWindowRect
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_altova_nativegui_NativeGUI
 * Method:    getForegroundWindow
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_altova_nativegui_NativeGUI_getForegroundWindow
  (JNIEnv *, jclass);

/*
 * Class:     com_altova_nativegui_NativeGUI
 * Method:    getCursorPos
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_altova_nativegui_NativeGUI_getCursorPos
  (JNIEnv *, jclass);

/*
 * Class:     com_altova_nativegui_NativeGUI
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_altova_nativegui_NativeGUI_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_altova_nativegui_NativeGUI
 * Method:    getWindowInfo
 * Signature: ()[[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_altova_nativegui_NativeGUI_getWindowInfo
  (JNIEnv *, jclass);

/*
 * Class:     com_altova_nativegui_NativeGUI
 * Method:    showWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_altova_nativegui_NativeGUI_showWindow
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
